spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/purchase_app_db?characterEncoding=utf8
    username: root
    password: kotlin
    driverClassName: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  mail:
    host: smtp.gmail.com
    port: 587
    username: hamada.tomoki03@gmail.com
    password: argon3-3
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
# ロギングに関する設定
logging:
  level:
    root: INFO
